import { PageHeader } from '../components/UI'

export function ApiGuidePage() {
  const origin = window.location.origin
  return <div className="page guide-page"><PageHeader title="接口文档" subtitle="API 地址与生图接入" />
    <section className="guide-section"><h2>连接地址</h2><dl className="detail-grid"><dt>服务地址</dt><dd><code>{origin}</code></dd><dt>认证方式</dt><dd>在 API 密钥页面创建密钥，并在请求头中使用 <code>Authorization: Bearer pst-...</code></dd><dt>模型名称</dt><dd>从模型广场选择模型；密钥所属分组必须包含该模型。</dd></dl><p>从其他设备调用时，把地址中的主机名替换为该设备可访问的服务器地址；端口保持与部署配置一致。</p></section>
    <section className="guide-section"><h2>异步生图</h2><p>提交后返回任务 ID 和状态。使用同一密钥轮询任务，状态为 <code>succeeded</code> 后获取图片。</p><pre>{[`POST ${origin}/v1/images/generations`, 'Authorization: Bearer pst-你的密钥', 'Idempotency-Key: 每次生成使用唯一值', 'Content-Type: application/json', '', '{', '  "model": "模型广场中的模型名",', '  "prompt": "一幅城市夜景插画",', '  "size": "1024x1024",', '  "n": 1', '}'].join('\n')}</pre><pre>{[`GET ${origin}/v1/jobs/{任务ID}`, `GET ${origin}/v1/jobs/{任务ID}/image`].join('\n')}</pre></section>
    <section className="guide-section"><h2>图生图与编辑生图</h2><p>使用同一个提交接口，将原图和编辑要求放在请求体中。<code>image</code> 填 PNG/JPEG 的 Base64 内容或 <code>data:image/png;base64,...</code>；<code>strength</code> 范围为 0 到 1，数值越大，改动越明显。每次新任务使用新的 Idempotency-Key。</p><pre>{[`POST ${origin}/v1/images/generations`, 'Authorization: Bearer pst-你的密钥', 'Idempotency-Key: 新任务的唯一值', 'Content-Type: application/json', '', '{', '  "model": "模型广场中的模型名",', '  "prompt": "把背景改为雨夜，保留人物姿态",', '  "size": "1024x1024",', '  "parameters": {', '    "action": "img2img",', '    "image": "data:image/png;base64,<原图Base64>",', '    "strength": 0.55,', '    "noise": 0', '  }', '}'].join('\n')}</pre></section>
    <section className="guide-section"><h2>局部重绘</h2><p>把需要修改的区域绘制在与原图同尺寸的 PNG 遮罩上。请求中同时提供 <code>image</code> 和 <code>mask</code>，服务会选择对应的 inpainting 模型；其余字段与图生图相同。</p><pre>{[`POST ${origin}/v1/images/generations`, 'Authorization: Bearer pst-你的密钥', 'Idempotency-Key: 新任务的唯一值', 'Content-Type: application/json', '', '{', '  "model": "模型广场中的模型名",', '  "prompt": "把窗外改成雪景",', '  "size": "1024x1024",', '  "parameters": {', '    "action": "infill",', '    "image": "data:image/png;base64,<原图Base64>",', '    "mask": "data:image/png;base64,<遮罩Base64>",', '    "strength": 0.7,', '    "inpaint_img2img_strength": 0.8', '  }', '}'].join('\n')}</pre><p>图片须为 PNG 或 JPEG 且不超过 12 MB；遮罩使用 PNG。以上模式只适用于支持相应功能的上游模型。</p></section>
    <section className="guide-section"><h2>参考图</h2><p>编辑时也可以附加风格参考图。<code>references</code> 最多 8 张；精准参考图使用 <code>precise_reference</code>，两者不能同时提供。</p><pre>{['"parameters": {', '  "action": "generate",', '  "references": [{', '    "image": "data:image/png;base64,<参考图Base64>",', '    "information_extracted": 1,', '    "strength": 0.6', '  }]', '}'].join('\n')}</pre></section>
    <section className="guide-section"><h2>酒馆生图配置</h2><dl className="detail-grid"><dt>生成方式</dt><dd>NovelAI → 第三方代理</dd><dt>代理 URL</dt><dd><code>{origin}/genarate</code></dd><dt>API 密钥</dt><dd>填写当前分组的 <code>pst-</code> 密钥</dd><dt>模型</dt><dd>填写模型广场中的公开模型名或有权限的专属模型名</dd></dl><p>酒馆的流式代理选项可以开启。代理接口会等待图片生成并返回可立即下载的短时效图片地址。</p></section>
    <section className="guide-section"><h2>模型列表与兼容接口</h2><pre>{[`GET ${origin}/v1/models`, 'Authorization: Bearer pst-你的密钥', '', `POST ${origin}/genarate`, 'Authorization: Bearer pst-你的密钥', 'Content-Type: application/json', '', '{"model":"模型名","prompt":"画面描述","size":"1024x1024"}'].join('\n')}</pre><p>所有时间按北京时间展示和筛选；费用以模型广场显示的分组定价为准。</p></section>
  </div>
}
